/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiamuyao_stujnidelete_MathKit */

#ifndef _Included_com_xiamuyao_stujni_MathKit
#define _Included_com_xiamuyao_stujni_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiamuyao_stujni_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiamuyao_stujni_MathKit_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
